name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the private repository (your Hugo source code)
      - name: Checkout Hugo repository
        uses: actions/checkout@v3

      # 2. Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      # 3. Build the Hugo site
      - name: Build Hugo site
        run: hugo --minify

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: francescocitti.com

