name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Or your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Install dependencies
        run: |
          # If you have any custom steps to install dependencies
          echo "Installing dependencies"

      - name: Build Hugo Site
        run: hugo --minify

      - name: Add CNAME file
        run: echo "francescocitti.com" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

