name: Publish to GH Pages
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_Linux-64bit.tar.gz'
          tar -C /usr/local/bin -xzvf /tmp/hugo.tar.gz hugo

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        run: |
          rm -rf ${GITHUB_WORKSPACE}/built-site
          mkdir -p ${GITHUB_WORKSPACE}/built-site
          cp -R public/* ${GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site
          git init
          git config user.name 'Francesco Citti'
          git config user.email 'myservices@francescocitti.com'
          git add .
          git commit --allow-empty -m 'Redeployed site'
          git branch -M gh-pages
          git remote add origin https://github.com/francescocitti/personal-website/
          git push --force origin gh-pages

